### ISSUE TITLE
Support for non-OpenAI models?

### ISSUE THREAD

**Issue by Boscop** [JackMatthewRimmer/rust-rag-toolchain#149]
Thanks for making this crate, it seems very useful :)
Would it be possible to make it work for non-OpenAI models (e.g. Claude 3.5 Sonnet), and maybe even integrate with https://crates.io/crates/genai ?

**Comment by JackMatthewRimmer** [comment]
Hi @Boscop I will take a look at trying to get the anthropic models as part of the library soon. Can I just confirm that this requirement would be via Anthopic's API and not something else like Amazon Bedrock ?

**Comment by Boscop** [comment]
@JackMatthewRimmer Yes, via Anthropic API :)
Thanks 🙏

**Comment by Boscop** [comment]
Also I'm interested in using embedding models of VoyageAI and MixedBread :)

**Comment by JackMatthewRimmer** [comment]
@Boscop I've closed this issue and Anthropic will be part of the next release. If there's anything else that you have as a feature request please could you raise separate tickets for those

**Comment by Boscop** [comment]
Ok thanks :)
