### ISSUE TITLE
Question about RAG examples: Shouldn't `pg_vector` and `basic_rag_chain` examples use the same embedding model?

### ISSUE THREAD

**Issue by Boscop** [JackMatthewRimmer/rust-rag-toolchain#151]
Is my understanding right, that the `pg_vector` example should be run before the `basic_rag_chain` example, to populate the vector store with the embeddings?

But that makes me wonder:
The `pg_vector` example uses the `OpenAIEmbeddingModel::TextEmbedding3Small` model to generate the embedding vectors.
But the `basic_rag_chain` example builds the `OpenAIEmbeddingClient` using the `TextEmbeddingAda002` model, thus for any RAG lookup with this client, it would use a different model to convert it to embedding vectors than the model that was used to generate the vectors it will be compared against, right?

<img width="594" alt="{D96677BC-BEC5-4B05-857C-AEC18BC803B7}" src="https://github.com/user-attachments/assets/af4a20f1-9728-4fc1-a3c1-12e88fa7494d">

**Comment by JackMatthewRimmer** [comment]
Hi @Boscop yes you are correct that you would want to use the same embedding model. For consistency Ill raise a pr to make them the same across the both examples to avoid any confusion in the future
