### ISSUE TITLE
Support for calling local OpenAI-compatible API server for generating embeddings

### ISSUE THREAD

**Issue by Boscop** [JackMatthewRimmer/rust-rag-toolchain#158]
I'm running LM Studio which exposes a local OpenAI-compatible API server that I want to use for generating embeddings.

Currently, the endpoint `OPENAI_EMBEDDING_URL` is hardcoded to `https://api.openai.com/v1/embeddings`.
Could you please make it configurable so that we can use local LLMs for embedding? 🙂
This would be very useful!

Thanks 🙏

**Comment by JackMatthewRimmer** [comment]
Hi @Boscop Ill get this in asap should be a quick turn around

**Comment by Boscop** [comment]
Thanks!

**Comment by JackMatthewRimmer** [comment]
@Boscop v0.1.9 now presents a set of constructors that allow for directly passing the URL in 😄

**Comment by Boscop** [comment]
Great, thanks!
