### ISSUE TITLE
Use interior mutability for the ChatHistoryChain

### ISSUE THREAD

**Issue by JackMatthewRimmer** [JackMatthewRimmer/rust-rag-toolchain#70]
currently requires someone to have a mutable reference and were just mutating a vector internall. Have a look at using something like Cell<T> for this

**Comment by Abraxas-365** [comment]
Hi, I have been developing a rust langchain library, maby it can help you https://github.com/Abraxas-365/langchain-rust

**Comment by JackMatthewRimmer** [comment]
Hi @Abraxas-365 Ill take a look thanks !

**Comment by JackMatthewRimmer** [comment]
Can also do this for the additional options on the open ai client
